def bbcLogo():
    print()
    print("====================================")
    print("====================================")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BBBBBB      BBBBBB      CC  C     ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("====================================")
    print("====================================")
    print()
bbcLogo()

def bbcProgramList():
    print("EastEnders is a British television soap opera, first broadcast on 19 February 1985.")
    print("EastEnders storylines examine the domestic and professional lives of the people who live and work in the fictional London Borough of Walford in the East End of London.")
    print()
    input("Press Enter to coninue")
    print()
    print("Doctor Who is a British science-fiction programme produced by the BBC. The programme depicts the adventures of the Doctor, a time-travelling humanoid alien.")
    print("He explores the universe in his TARDIS, a time-travelling space ship.")
    print("Its exterior appears as a blue British police box.")
    print()
    input("Press Enter to coninue")
    print()
    print("Sherlock is a British television crime drama that presents a contemporary adaptation of Sir Arthur Conan Doyle's Sherlock Holmes detective stories")
    print("Created by Steven Moffat and Mark Gatiss, it stars Benedict Cumberbatch as Sherlock Holmes and Martin Freeman as Doctor John Watson.")
    print()
    input("Press Enter to coninue")
    print()
    print("Waterloo Road is a British television drama series set in a Scottish comprehensive school of the same name.")
    print("Following the seventh series, the show relocated to its current setting of Greenock Academy in Scotland after the eventual demolition of the previous location in Rochdale.")
    print()
    input("Press Enter to end the program")
bbcProgramList()

def bbcLogo():
    print()
    print("====================================")
    print("====================================")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BBBBBB      BBBBBB      CC  C     ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("====================================")
    print("====================================")
    print()
bbcLogo()
